/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fMenuAdmin.java
 *
 * Created on 22/07/2013, 10:19:49 AM
 */

package GUI;



/**
 *
 * @author ALUMNO-15
 */
public class fMenuAdmin extends javax.swing.JFrame {
    String[] nombreColumnasArticulos = {"Clave","Precio","Descripcion","Tipo"};
    String[] nombreColumnasClientes = {"nombre", "apellidos","direccion","telefono","tipo","inicio","sucursal"};
    String[] nombreColumnasEmpleados = { "nombre","apellidos","direccion","telefono","cargo","sucursal","nombreUsuario","password"};
    String[] nombreColumnasPeliculas = { "clave","precio","descripcion","tipo","titulo","clasificacion","genero","formato","direccion","año","pais","idioma","subtitulos","venta"};
    String[] nombreColumnasVideojuegos = { "clave","precio","descripcion","tipo","titulo","clasificacion","genero","formato","plataforma","no jugadores","venta"};
    String[] nombreColumnasVentas = {"noTransaccion", "articulo", "cantidad", "total"}; 
    String[] nombreColumnasRentas = {"noTransaccion", "articulo", "inicio","entrega"}; 
    String[] nombreColumnasTransacciones = {"nombreUsuario","fecha","noMembresia","sucursal","artTotal","total"}; 
    /** Creates new form fMenuAdmin */
    public fMenuAdmin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fMenu = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        fTabla = new javax.swing.JTable();
        fNuevo = new javax.swing.JButton();
        fModificar = new javax.swing.JButton();
        fEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        fMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Articulos", "Videojuegos", "Peliculas", "Rentas", "Ventas", "Transacciones", "Clientes", "Empleados" }));

        jScrollPane1.setViewportView(fTabla);

        fNuevo.setText("Nuevo...");
        fNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNuevoActionPerformed(evt);
            }
        });

        fModificar.setText("Modificar");

        fEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(fMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNuevo)
                    .addComponent(fModificar)
                    .addComponent(fEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNuevoActionPerformed
        fArticulo arti = new fArticulo();
        String opc=(String)fMenu.getSelectedItem();
        switch(opc){
            case "Articulos":
                arti.setVisible(true);
            break;
        }
        
    }//GEN-LAST:event_fNuevoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fEliminar;
    private javax.swing.JComboBox fMenu;
    private javax.swing.JButton fModificar;
    private javax.swing.JButton fNuevo;
    private javax.swing.JTable fTabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
