/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fMenuAdmin.java
 *
 * Created on 22/07/2013, 10:19:49 AM
 */

package GUI;

import control.Conexion;
import entidades.Articulo;
import entidades.Cliente;
import javax.swing.JTable;



/**
 *
 * @author ALUMNO-15
 */
public class fMenuAdmin extends javax.swing.JFrame {
    String[] nombreColumnasArticulos = {"Clave","Precio","Descripcion","Tipo"};
    String[] nombreColumnasClientes = {"nombre", "apellidos","direccion","telefono","tipo","inicio","sucursal"};
    String[] nombreColumnasEmpleados = { "nombre","apellidos","direccion","telefono","cargo","sucursal","nombreUsuario","password"};
    String[] nombreColumnasPeliculas = { "clave","precio","descripcion","tipo","titulo","clasificacion","genero","formato","direccion","año","pais","idioma","subtitulos","venta"};
    String[] nombreColumnasVideojuegos = { "clave","precio","descripcion","tipo","titulo","clasificacion","genero","formato","plataforma","no jugadores","venta"};
    
    Conexion conec;
    /** Creates new form fMenuAdmin */
    public fMenuAdmin() {
        initComponents();
        conec = new Conexion("iMovie","clustersito");
        conec.abrirConexion();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMenu = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        fTabla = new javax.swing.JTable();
        fNuevo = new javax.swing.JButton();
        fModificar = new javax.swing.JButton();
        fEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        lMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Articulos", "Videojuegos", "Peliculas", "Clientes", "Empleados" }));
        lMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lMenuActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(fTabla);

        fNuevo.setText("Nuevo...");
        fNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNuevoActionPerformed(evt);
            }
        });

        fModificar.setText("Modificar");
        fModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fModificarActionPerformed(evt);
            }
        });

        fEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addComponent(lMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNuevo)
                    .addComponent(fModificar)
                    .addComponent(fEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNuevoActionPerformed
        fArticulo arti = new fArticulo();
        
        String opc=(String)lMenu.getSelectedItem();
        switch(opc){
            case "Articulos":
                arti.setVisible(true);
            break;
                
            case "Clientes":
                fClientes cliente = new fClientes();
                cliente.setVisible(true);
            break;
            
            case "Empleados":
                fUsuarios usuario = new fUsuarios();
                usuario.setVisible(true);
            break;
            
            case "Videojuegos":
                arti.setVisible(true);
            break;
            
            case "Peliculas":
                arti.setVisible(true);
            break;
        }
        
    }//GEN-LAST:event_fNuevoActionPerformed

    private void lMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lMenuActionPerformed
        if (lMenu.getSelectedIndex() == 0){
            fTabla = new JTable(conec.guardarArticulo(),nombreColumnasArticulos);//asi se muestran los datos en la tabla, la tabla no es editable
        }
        if (lMenu.getSelectedIndex() == 1){
            fTabla = new JTable(conec.guardaVideojuego(),nombreColumnasVideojuegos);
        }
        if (lMenu.getSelectedIndex() == 2){
            fTabla = new JTable(conec.guardarPelicula(),nombreColumnasPeliculas);
        }
        if (lMenu.getSelectedIndex() == 3){
            fTabla = new JTable(conec.guardarCliente(),nombreColumnasClientes);
        }
        if (lMenu.getSelectedIndex() == 4){
            fTabla = new JTable(conec.guardaUsuario(),nombreColumnasEmpleados);
        }
        
    }//GEN-LAST:event_lMenuActionPerformed

    private void fModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fModificarActionPerformed
         
        String opc=(String)lMenu.getSelectedItem();
        switch(opc){
            case "Articulos":
                
            break;
                
            case "Clientes":
                String[] datosLeidos = {
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 0)),
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 1)),
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 2)),
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 3)),
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 4)),
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 5)),
                    String.valueOf(fTabla.getValueAt(fTabla.getSelectedRow(), 6))
                };
                Cliente cliente = new Cliente( datosLeidos[0],datosLeidos[1],datosLeidos[2],datosLeidos[3],datosLeidos[4],datosLeidos[5],datosLeidos[6]);
                conec.modificarCliente(cliente);
                
            break;
            
            case "Empleados":
                
            break;
            
            case "Videojuegos":
                
            break;
            
            case "Peliculas":
                
            break;
        }
         
    }//GEN-LAST:event_fModificarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fEliminar;
    private javax.swing.JButton fModificar;
    private javax.swing.JButton fNuevo;
    private javax.swing.JTable fTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lMenu;
    // End of variables declaration//GEN-END:variables

}
